### ISSUE TITLE
Missing required secret OPENAI_API_KEY in PR workflow

### ISSUE THREAD

**Issue by xwxtwd** [ai16z/eliza#1027]
**Describe the bug**
Missing required secret OPENAI_API_KEY in PR workflow configuration, which causes the workflow to fail when running [integration-tests](https://github.com/ai16z/eliza/actions/runs/12301919452/job/34333562742?pr=1011#logs) tasks.

**To Reproduce**

[integration-tests](https://github.com/ai16z/eliza/actions/runs/12301919452/job/34333562742?pr=1011#logs)

**Expected behavior**

This PR workflow should continue running

**Screenshots**
![image](https://github.com/user-attachments/assets/b8220bb6-2e9f-46c5-80a0-13433c98ac8d)

**Additional context**

This secret is essential for any workflows that interact with OpenAI's API. Without this configuration, all PR checks that require OpenAI integration will fail.

**Comment by BalanaguYashwanth** [comment]
Is this Issue resolved @pgoos ?
