### ISSUE TITLE
Unexpected token 'A', "Agent not found" is not valid JSON

### ISSUE THREAD

**Issue by cipherkilledit** [ai16z/eliza#1059]
**Describe the bug**

When "llama_local" is set as the modelProvider in the character.json file, a prompt returns this error: 

```
Error fetching response: SyntaxError: Unexpected token 'A', "Agent not found" is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5731:19)
    at successSteps (node:internal/deps/undici/undici:5712:27)
    at fullyReadBody (node:internal/deps/undici/undici:4609:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async consumeBody (node:internal/deps/undici/undici:5721:7)
    at async handleUserInput (file:///home/cipher/cipher/agent/src/index.ts:454:22)
    at async file:///home/cipher/cipher/agent/src/index.ts:420:13
```

**To Reproduce**

1. In any character.json file, set the modelProvider to "llama_local"
2. Initialize your character
3. Send a prompt, such as "hello"

**Expected behavior**

I expected the character to respond back with a greeting such as hi, hello, how are you, etc.

**Screenshots**

![image](https://github.com/user-attachments/assets/f871b6f0-1b64-413a-bf7f-63139e67f643)

**Additional context**

Using WSL with release: https://github.com/ai16z/eliza/releases/tag/v0.1.5-alpha.5

**Comment by cipherkilledit** [comment]
@lalalune what was the resolution...? Many users are still having issues using llama_local.

**Comment by corbinabeebe** [comment]
@lalalune What was the resolution for this issue?

**Comment by Lama1403** [comment]
I get similar issue but  Unexpected token 'H', "Here is my"... is not valid JSON
    at JSON.parse

**Comment by innovinitylabs** [comment]
Error fetching response: SyntaxError: Unexpected token 'A', "Agent not found" is not valid JSON
    at JSON.parse (<anonymous>)

same issue here too, am using opnrouter api key

**Comment by jack-landon** [comment]
It's due to pnpm v10 attempting to build a the better-sqlite3 db.

Run `pnpm approve builds`.
You'll get a dropdown -> select `better-sqlite3`, and try again.
