### ISSUE TITLE
Discord agents knock each other out of VC

### ISSUE THREAD

**Issue by vincentskele** [ai16z/eliza#1145]
**Describe the bug**

When running two agents in the same client one will join the discord voice channel and then when 2nd agent joins it kicks the first agent out of discord

**Additional context**

- whichever character is listed last is the one that stays in the voice channel
- the same thing happens even if sending the agents to different voice channels. 
- only tested from 1 discord server, 2 unique servers may produce a different outcome

**Comment by shakkernerd** [comment]
Hi @vincentskele there is a potential fix in #1156 that is already merged into `develop` branch.
Kindly try that and give feedback.

**Comment by vincentskele** [comment]
ran into some other issues with develop but the conflict with discord is resolved!

**Comment by shakkernerd** [comment]
Thanks for the feedback. 
What are the other issues?

**Comment by vincentskele** [comment]
all resolved now with latest pull from develop
