### ISSUE TITLE
pnpm install fails on m1 mac 

### ISSUE THREAD

**Issue by santekotturi** [ai16z/eliza#1146]
I've spent the last 6 hours trying to get around this

same error with both: 
`pnpm install` and `pnpm install -w --include=optional sharp`

```
│   LIBTOOL-STATIC Release/opus.a
│   CXX(target) Release/obj.target/opus/src/node-opus.o
│ In file included from <built-in>:495:
│ <command line>:19:14: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
│    19 | #define POSIX,__STDC_FORMAT_MACROS 1
│       |              ^
│ In file included from ../src/node-opus.cc:1:
│ /Users/santekotturi/Developer/forecast/eliza/node_modules/node-addon-api/napi.h:14:10: fatal error: 'functional' …
│    14 | #include <functional>
│       |          ^~~~~~~~~~~~
│ 1 warning and 1 error generated.
│ make: *** [Release/obj.target/opus/src/node-opus.o] Error 1
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack at ChildProcess.<anonymous> (/Users/santekotturi/.local/share/pnpm/global/5/.pnpm/pnpm@9.9.0/node_…
│ gyp ERR! System Darwin 24.1.0
│ gyp ERR! command "/Users/santekotturi/.nvm/versions/node/v23.4.0/bin/node" "/Users/santekotturi/.local/share/pnpm…
│ gyp ERR! cwd /Users/santekotturi/Developer/forecast/eliza/node_modules/@discordjs/opus
│ gyp ERR! node -v v23.4.0
│ gyp ERR! node-gyp -v v10.1.0
│ gyp ERR! not ok 
│ node-pre-gyp ERR! build error 
│ node-pre-gyp ERR! stack Error: Failed to execute '/Users/santekotturi/.nvm/versions/node/v23.4.0/bin/node /Users/…
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/santekotturi/Developer/forecast/eliza/node_module…
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
│ node-pre-gyp ERR! System Darwin 24.1.0
│ node-pre-gyp ERR! command "/Users/santekotturi/.nvm/versions/node/v23.4.0/bin/node" "/Users/santekotturi/Develope…
│ node-pre-gyp ERR! cwd /Users/santekotturi/Developer/forecast/eliza/node_modules/@discordjs/opus
│ node-pre-gyp ERR! node -v v23.4.0
│ node-pre-gyp ERR! node-pre-gyp -v v0.4.5
│ node-pre-gyp ERR! not ok 
```

always using `rm -rf node_modules & rm pnpm-lock.yaml` between each try.

node v23.4.0
tried downgrading to v20.x 
pnpm v9.9.0

also tried `brew install opus`
macOS 15.1 
XCode 16.2

on:
`% git status >> HEAD detached at v0.1.6-alpha.1`

Potentially related to:
https://github.com/ai16z/eliza/issues/1041
https://github.com/ai16z/eliza/issues/215

**Comment by oxSaturn** [comment]
Have you tried `xcode-select --install` to have C++ compiler installed? I'm on m2, thought I ran into a similar issue (don't remember the exact issue) when I was trying eliza first time, and running `xcode-select --install` got it fixed for me as far as I can remember.

**Comment by santekotturi** [comment]
Yea, I ran that, I've got a macos 15.2 update waiting for me, maybe that plays better with Xcode 16.2... will report back

**Comment by santekotturi** [comment]
macos 15.2 updated, all xcode tool updates made. still same error. 

This discordjs/opus connects having homebrew python3.12 in your path (which I do) https://github.com/discordjs/opus/issues/145#issuecomment-2250719870

Curious what anyone else has for 

```
python3 --version
which python3
```

**Comment by santekotturi** [comment]
Had to uninstall xcode-select and reinstall   ¯\_(ツ)_/¯ 
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

that gets us: `node_modules/@discordjs/opus: Running install script, done in 30.1s`

**Comment by rossixiluo** [comment]
I have the same issue. Have you resolved? Thanks.

**Comment by 0xTenable** [comment]
Have the same issue as well, but for node-llama-cpp on M1 macbook

**Comment by Buooy** [comment]
> Have the same issue as well, but for node-llama-cpp on M1 macbook

If you are coming from intel to silicon chip. one of the most common problems is porting over node and running it with rosetta. A lot of the AI packages are going to break.

**1. Firstly, check if you are running a node version that's for x64 or arm...**
`node -p "process.arch"`

You are looking for `arm64`. If you are on `x64`, you need to delete and reinstall node

**2. Delete and reinstall node v23 (for this repo)**
- Follow this: https://medium.com/@mathankumar.mkk29/uninstall-nodejs-from-macos-step-by-step-guide-5415dd79a98d
- Then redownload and install: https://nodejs.org/en/download/package-manager

GLHF

**Comment by Zezzzzz** [comment]
> Have the same issue as well, but for node-llama-cpp on M1 macbook

`env /usr/bin/arch -arm64 /bin/zsh —-login`

Run the following to switch to arm64

**Comment by lucasdutracoelho** [comment]
****UPDATE

I managed to complete the build on macOS! 🚀
However, I had to make some changes to the project:
	•	Removed the client-discord package.
	•	Added the following override to pnpm in the package.json file:

`"pnpm": {
  "overrides": {
    "@ai-sdk/provider": "1.0.1"
  }
}`

I hope this information helps! Let me know if you need anything else.

**Comment by BenBish** [comment]
> Had to uninstall xcode-select and reinstall ¯_(ツ)_/¯
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install
> ```
> 
> that gets us: `node_modules/@discordjs/opus: Running install script, done in 30.1s`

Incredibly, this worked for me. Unbelievably fast afterwards! Thank you.
