### ISSUE TITLE
REQUIRED_NODE_VERSION: No such file

### ISSUE THREAD

**Issue by tcotten-scrypted** [ai16z/eliza#1151]
**Describe the bug**

Following directions in README.md with `sh scripts/start.sh` on Ubuntu causes an error:

scripts/start.sh: 6: cannot open REQUIRED_NODE_VERSION: No such file

**To Reproduce**

Environment: Ubuntu 24.04 LTS
1. `sh scripts/start.sh`

**Expected behavior**

No error regarding the variable "REQUIRED_NODE_VERSION"

**Screenshots**

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/4280583e-0dc2-4c49-833c-84faaae86412" />

**Additional context**

This is a simple issue caused by the shell script being executed with dash instead of bash.

**Comment by tcotten-scrypted** [comment]
Was it an intentional choice to not include a bash shebang in the startup.sh script? It's got a lot of bashy stuff that dash doesn't like.

**Comment by tcotten-scrypted** [comment]
On Ubuntu, executing with bash directly instead of dash solves the issue.

**Comment by shakkernerd** [comment]
Hi @tcotten-scrypted I just updated the start script, it should fix the issue.
Thanks for reporting!

**Comment by tcotten-scrypted** [comment]
Confirming resolved for Ubuntu environment.
