### ISSUE TITLE
pnpm start --character="characters/trump.character.json"

### ISSUE THREAD

**Issue by whgreate** [ai16z/eliza#1161]
**Describe the bug**

**To Reproduce**
1. add  "clients": ["twitter"], to trump.character.json
2. pnpm start --character="characters/trump.character.json"
3. error: `Killed
/workspaces/eliza_1/agent:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @ai16z/agent@0.1.5-alpha.6 start: `node --loader ts-node/esm src/index.ts "--isRoot" "--character=characters/trump.character.json"`
Exit status 137
 ELIFECYCLE  Command failed with exit code 137.`

**Comment by shakkernerd** [comment]
Hi there, you seem to be using an older version (`0.1.5-alpha.6`).
Kindly update to latest (`0.1.6-alpha.4`).

**Comment by whgreate** [comment]
don't understand how to do that, I'm on develop branch.

**Comment by kurbaitaev** [comment]
@whgreate git checkout $(git describe --tags --abbrev=0)
