### ISSUE TITLE
SCAM project

### ISSUE THREAD

**Issue by yjyu1997** [ai16z/eliza#1286]
First of all, these are not the same projects at all. 
Secondly, this is a project from 2023. 
Then, why don't you try streaming yourself writing code?
 Lastly, could you please take a look at your own crappy project, eliza.Js? 
Wrapping something up and calling it AI?
It‘s a SCAM!!!

**Comment by lalalune** [comment]
You are retarded

Here is me streaming writing code and teaching how the framework works: https://x.com/shawmakesmagic/status/1866011309499920521

Banning you from our repo, get the fuck out
