### ISSUE TITLE
http proxy error /agents

### ISSUE THREAD

**Issue by Wubnar** [ai16z/eliza#1322]
**Describe the bug**

PS C:\Users\---\Desktop\eliza-main> pnpm start:client

> eliza@ start:client C:\Users\---\Desktop\eliza-main
> pnpm --dir client dev

> eliza-client@0.1.6 dev C:\Users\---\Desktop\eliza-main\client
> vite

  VITE v5.4.11  ready in 484 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
(node:23000) ExperimentalWarning: CommonJS module C:\Users\---\Desktop\eliza-main\node_modules\tailwindcss\lib\lib\load-config.js is loading ES Module C:\Users\---\Desktop\eliza-main\client\tailwind.config.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2:00:41 AM [vite] http proxy error: /agents
Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)

**Comment by SukhachevN** [comment]
Hi! I have the same issue. How did you solve it?

**Comment by happylolonly** [comment]
> Hi! I have the same issue. How did you solve it?

had the same, was needed to run `pnpm start` first
