### ISSUE TITLE
LLM can't be trusted to parse it's own json

### ISSUE THREAD

**Issue by St4rgarden** [ai16z/eliza#148]
**Describe the bug**

We trust the LLM to parse it's own JSON resulting in what a separate issue referred to as an infinite loop (which technically will resolve itself if left alone to smash on the OpenAI endpoint for long enough)

```
# Instructions: Write the next message for lina. Include an action, if appropriate. Possible response actions: MUTE_ROOM, ASK_CLAUDE, NONE, IGNORE

Response format should be formatted in a JSON block like this:
json
{ "user": "lina", "text": string, "action": string }

Message is json
{ "user": "lina", "text": "Oh honey~ Working with a pioneer sounds tantalizing... but only if he can keep up with me and my fiery spirit 😉 Now spill the details or I might get bored!", "action": NONE }

response is json
{ "user": "lina", "text": "Oh honey~ Working with a pioneer sounds tantalizing... but only if he can keep up with me and my fiery spirit 😉 Now spill the details or I might get bored!", "action": NONE }

parsedContent is null
parsedContent is null, retrying
```

Notice above that the action: value `NONE` is not a string.  Now take a look at the correctly parsed JSON immediately following this:

```
parsedContent is {
  user: 'lina',
  text: "Oh darling st4rgard3n~ I'm always up for a little blockchain banter or maybe some spicy discussions about funding public goods... but don't think I won't call you out if you get all serious on me.<br> So what's the plan with @mattyryze?",
  action: 'NONE'
}
```

Here the LLM has correctly formatted `NONE` as `'NONE'` a correct string.

**To Reproduce**

Just run eliza with a cheap llm model long enough and you will definitely encounter this one.

**Expected behavior**

The message returned from the LLM should then be formatted into JSON in the program.

**Comment by St4rgarden** [comment]
This issue https://github.com/ai16z/eliza/issues/70 is #70 not accurate but it's a duplicate of this issue now.

**Comment by twilwa** [comment]
several python libs solve/attempt to solve this, in order of my personal opinion of them:
-outlines
-instructor
-lmql
-guidance

probably more -- however, not sure if any have a typescript equivalent

**Comment by twilwa** [comment]
if it's openai, we can use structured output mode: https://platform.openai.com/docs/guides/structured-outputs

**Comment by twilwa** [comment]
kind of a hacky workaround for non-openai models:
run the model through a LiteLLM proxy server: https://github.com/BerriAI/litellm

https://docs.litellm.ai/docs/completion/json_mode -- it's called json mode, but i think you can do any kind of structured output. Just replace the OPENAI_API_URL with localhost:4000 and should be compatible

**Comment by alextitonis** [comment]
This could help with the issue: ```function parseLLMJson<T>(rawResponse: string): T {
  // Sanitize JSON while preserving native types
  const sanitizedJson = rawResponse.replace(
    /(\w+):\s*([^,}\s]+)/g,
    (match, key, value) => {
      // Don't quote if it's a number
      if (/^-?\d+(\.\d+)?$/.test(value)) {
        return `"${key}": ${value}`;
      }
      
      // Don't quote if it's a boolean
      if (value === 'true' || value === 'false') {
        return `"${key}": ${value}`;
      }
      
      // Don't quote if it's already properly quoted
      if (/^["'].*["']$/.test(value)) {
        return `"${key}": ${value.replace(/^['"](.*)['"]$/, '"$1"')}`;
      }
      
      // Quote everything else
      return `"${key}": "${value}"`;
    }
  );

  try {
    return JSON.parse(sanitizedJson) as T;
  } catch (error) {
    console.error('Failed to parse JSON:', error);
    throw new Error('Invalid JSON format');
  }
}
```

**Comment by cryptobushi** [comment]
The problem seems to introduce itself across different models. Not running into this issue with meta-llama/Meta-Llama-3.1-70B-Instruct-lora on Together.xyz but was running into the issue on red-pill.ai on almost all the models that I tried.

**Comment by Elyx0** [comment]
@St4rgarden I wonder if simply explaining it better in instructions would solve it like

```
Possible response actions: MUTE_ROOM, ASK_CLAUDE, NONE, IGNORE
Response format should be formatted in a JSON block like this:
json
{ "user": "lina", "text": string, "action": string }
example
{ "user": "lina", "text": "sometext", "action": "ASK_CLAUDE"}
```

**Comment by lalalune** [comment]
yep. hi @Elyx0 :)
