### ISSUE TITLE
Chattiness Slider/Respond to Bots setting in Discord

### ISSUE THREAD

**Issue by twilwa** [ai16z/eliza#157]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/ef57908e-59cb-480a-8f7d-821a3468bce7)

Bots will dump tokens responding to each other and/or be annoyingly chatty sometimes

**Describe the solution you'd like**
 -- I think it might be useful to have a setting where a bot will 'wait' X amount of time before responding to a message, or a way to weight boredom higher in a series of rapid-fire back and forths. Maybe an if chars = 250+ and responsetime>1000ms then multiply normal boredom by X (or however fast humans aren't able to write) + some manual sliders on chattiness levels if we want one that's more shy vs outgoing
 

When interacting with another bot, or set as anxious/shy/quiet, response volume is reduced by ~50%

**Describe alternatives you've considered**
none, just had the thought

**Additional context**

![image](https://github.com/user-attachments/assets/7adf326c-9f6f-4756-825c-8c5e5b1d2bed)

**Comment by twilwa** [comment]
https://sourcegraph.com/github.com/vertyco/vrt-cogs@main/-/blob/assistant/listener.py

an existing implementation in a different framework in python; since they have the app identifier, it should be fairly straightforward, i think

**Comment by lalalune** [comment]
We can do this with a provider or hardcode it.

The boredom module should prevent this but needs to be tuned.

**Comment by lalalune** [comment]
We added prompt template overrides per character
