### ISSUE TITLE
Fix function calling, repetition and local action calling

### ISSUE THREAD

**Issue by lalalune** [ai16z/eliza#161]
The local model could be dramatically better. Currently it struggles with repeating forever, getting action names wrong something and not structuring JSON format properly (although usually its just the repeats that kill it)

This could be dramatically improved as an experience through a combination of model and prompt setting optimization, although an advanced researcher may also have a model-side approach.

<img width="750" alt="Screenshot 2024-11-01 at 4 06 33 PM" src="https://github.com/user-attachments/assets/a3d3def6-19e0-432e-8194-ae0e49389d71">

**Comment by MERNinja** [comment]
@lalalune is it resolved? what's the fix?
I am still facing the same issue on my AWS VM

![image](https://github.com/user-attachments/assets/f8322705-81ca-4894-8878-7ddeb72ac186)
