### ISSUE TITLE
Prompt template overrides

### ISSUE THREAD

**Issue by michaelsharpe** [ai16z/eliza#166]
**Is your feature request related to a problem? Please describe.**

I am modifying core templates from different providers to alter the style of thinking for my agent and control all aspects of its prompting.

**Describe the solution you'd like**

Override prompt templates in the character file for all prompts (twitter generation, search, interaction, etc)

**Describe alternatives you've considered**

Diverging (which would suck).

**Comment by lalalune** [comment]
Merged, can add template overrides into character files
