### ISSUE TITLE
Telegram bot not returning responses

### ISSUE THREAD

**Issue by rhlsthrm** [ai16z/eliza#178]
**Describe the bug**

Does not respond to messages, just prints forever in the console.

**To Reproduce**

* Load custom character file from `tweets2character`.
* Set up Telegram bot token.
* Try to chat with bot.

**Expected behavior**

Bot responds.

**Screenshots**
Prints these logs forever.
<img width="1282" alt="Screenshot 2024-11-03 at 17 15 48" src="https://github.com/user-attachments/assets/1e32781d-de76-4a50-a53f-026d15b9d799">

**Additional context**

Running with LlamaLocal model.

**Comment by lalalune** [comment]
I justed tested degen spartan and it seems to work gud now
