### ISSUE TITLE
Changelog generator

### ISSUE THREAD

**Issue by madjin** [ai16z/eliza#181]
**Is your feature request related to a problem? Please describe.**

https://keepachangelog.com/en/1.1.0/

**Describe the solution you'd like**

https://github.com/github-changelog-generator/github-changelog-generator

**Describe alternatives you've considered**

https://github.com/github-changelog-generator/github-changelog-generator/wiki/Alternatives

**Additional context**

- would need a github token to use this: https://github.com/github-changelog-generator/github-changelog-generator?tab=readme-ov-file#github-token

Attaching a sample changelog
[CHANGELOG.md](https://github.com/user-attachments/files/17612217/CHANGELOG.md)

**Comment by sirkitree** [comment]
I think this would be a great addition to the the automated release notes that come with Github when creating a release from a tag.

**Comment by madjin** [comment]
Haven't tested yet but this one looks useful for that: https://github.com/mikepenz/release-changelog-builder-action

**Comment by sirkitree** [comment]
Taking a stab at making this a github action that will run when we create a new tag.

**Comment by sirkitree** [comment]
Still working to get this right - I have a github action setup which generates the file, now I need to get it to commit the file automatically.

**Comment by sirkitree** [comment]
success!

sorry for the noise of the bogus tags, but it took some testing

https://github.com/ai16z/eliza/blob/main/CHANGELOG.md
