### ISSUE TITLE
Docs review

### ISSUE THREAD

**Issue by sirkitree** [ai16z/eliza#201]
## Homepage
![Image](https://github.com/user-attachments/assets/39c26715-9400-4b90-8816-d5e363dcb023)
* ... designed to be ~~and~~ easy to use (strike the 'and')

![Image](https://github.com/user-attachments/assets/135f0e0a-d760-46d1-b7c4-31c60d915727)
* This discord invite is invalid.

![Image](https://github.com/user-attachments/assets/b3dd900f-3252-40ae-a575-a81afadf845c)
* Just curious, but what is the "b" icon? Should we make like an AI one? or is this something to do with the docs framework?

## API
* In general, API docs typically have a standard format that provides the interface, parameters, endpoints, etc. for something like a REST API. So when clicking this, I was not expecting to see setup instructions. It seems like this is mostly duplicate info from the "[Getting Started](https://ai16z.github.io/eliza/docs/quickstart/)" section. There isn't really an API, so I'd suggest we just remove this section for now.
* Possibly replace with with some documentation about how the core information flows from the Agent Runtime, to the Memory System, the Room-based Organization, Information Processing Pipeline, Provider Integration, and State Management - though these could all be valid sections under the Advanced Concepts section as well on the Documentation page.

![Image](https://github.com/user-attachments/assets/55c6d401-9b6b-4f49-90f7-528ffb4acefb)
*  banner image is broken

**Comment by madjin** [comment]
I did a huge overhaul of docs, still much more to do (looking around for a new icon/logo to replace that b)

https://ai16z.github.io/eliza/docs/intro/

Some to-do plans:
- prettify overall (icons to table of contents)
- add some architecture diagrams (LLM -> mermaid diagram)
- improve api docs (make code more readable / add comments for better autodocs)
  - generate code2prompt templates: https://github.com/raphaelmansuy/code2prompt
- test and ensure documentation is up to date (go through everything after refactor code merges)
- add more visuals
