### ISSUE TITLE
build docs locally gives errors

### ISSUE THREAD

**Issue by yodamaster726** [ai16z/eliza#202]
When I build the docs folder locally I get a bunch of errors and it doesn't render.

Using the latest code as of 11/4/2024 - 10pm EST

I ran `pnpm run dev` and got these errors:

![image](https://github.com/user-attachments/assets/3256a453-1e69-446c-8eac-d2afc5709e91)

`pnpm run dev` gave me this output

> eliza-docs@0.0.0 dev /Users/yoda26/Documents/Projects/eliza-yodamaster726/docs
> docusaurus start --port 3002 --no-open

[INFO] Starting the development server...
[96m[info][0m Loaded plugin typedoc-plugin-markdown
[93m[warning][0m The glob ./src/index.ts did not match any files
[91m[error][0m Unable to find any entry points. See previous warnings
[SUCCESS] Docusaurus website is running at: http://localhost:3002/eliza/
[webpackbar] ℹ Compiling Client
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Action.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (DatabaseAdapter.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Evaluator.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Provider.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Action.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (DatabaseAdapter.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (MemoryManager.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Evaluator.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (MemoryManager.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (MemoryManager.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (MemoryManager.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Provider.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Actor.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Evaluator.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Goal.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Memory.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Memory.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Memory.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Memory.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Message.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Actor.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Evaluator.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Goal.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Memory.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Memory.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Memory.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Memory.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Message.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/State.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Message.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Content.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/State.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Action.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Provider.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[WARNING] Docs markdown link couldn't be resolved: (../interfaces/Evaluator.md) in source file "/Users/yoda26/Documents/Projects/eliza-yodamaster726/docs/api/classes/AgentRuntime.md" for version current
[webpackbar] ✔ Client: Compiled successfully in 6.53s
client (webpack 5.96.1) compiled successfully
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies

**Comment by lalalune** [comment]
Yeah its weird, seems to make the mds but cuts off at that part, seems to be related to how some files are compiled in the docusaurus mdx typedoc chain. Maybe updating could fix.

**Comment by madjin** [comment]
I fixed, try now

**Comment by yodamaster726** [comment]
works good now.  thanks for fixing.

verified with node 23.1
