### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by lalalune** [ai16z/eliza#21]
Telegram bot so people can interact with Spartan in the TG

Needs to ignore other bots and not be annoying

**Comment by sirkitree** [comment]
There are a couple of functions related to this already in index.ts (eg. https://github.com/ai16z/eliza/blob/main/src/index.ts#L130)

But there doesn't seem to be a way to 
1. specify it in the character profile or
1. put in credentials / pointers to a chan

Looks like there is a client already as well: https://github.com/ai16z/eliza/tree/main/src/clients/telegram

I think perhaps this all just needs pulled together and tested?

**Comment by sirkitree** [comment]
related: #35
