### ISSUE TITLE
pnpm install fails on Ubuntu

### ISSUE THREAD

**Issue by lo-zed** [ai16z/eliza#215]
**Describe the bug**

Installation fails

**To Reproduce**

`pnpm i`

**Expected behavior**

Installs without error.

**Additional context**

OS: Ubuntu 24.04 LTS
node: v22.10.1
pnpm: 9.12.3

An example of error I get:
```
node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
└─ Failed in 283ms at /home/ubuntu/eliza/node_modules/sharp
```
Happens with `@discordjs/opus` & `onnxruntime-node` too, maybe others.

But if I go into the directory and install from there it works:
```
cd node_modules/sharp
npm install
```
This doesn't throw any error and installs the package correctly.

Is this a bug on `pnpm` side?

**Comment by Sid31** [comment]
Did you try pnpm install --include=optional sharp ?

**Comment by lo-zed** [comment]
yes, same error unfortunately

**Comment by lo-zed** [comment]
issue created at pnpm repo too: https://github.com/pnpm/pnpm/issues/8737

**Comment by metadiver** [comment]
I run into the same issue. installing python and adding it into the path worked for me. https://www.python.org/downloads/

**Comment by metadiver** [comment]
related https://github.com/ai16z/eliza/issues/237

**Comment by lo-zed** [comment]
Hi, thanks for your help. I tried but with no success. How do you add python to the path? I tried:
- a bash alias
- a link python -> python3
- adding the python path to `.env` in the project base dir

Also would you know how to get useful debug info? I tried `--reporter ndjson` but couldn't find the reason why the install fails

**Comment by sirkitree** [comment]
Try the following:
1. downgrade to node v20 `nvm install 20 && nvm use 20`
1. remove node modules and lock file `rm -rf node_modules && rm pnpm-lock.yaml`
1. rerun install `pnpm i`

**Comment by sais-github** [comment]
I was running into the same issue, 
`apt update`
`apt install -y build-essential` 
Resolved the error
