### ISSUE TITLE
Fix memory mixing in Twitter generate

### ISSUE THREAD

**Issue by lalalune** [ai16z/eliza#23]
Twitter generate uses a default room ID and this might be causing problems between the clients, since they access the same sqlite database. So Spartan would say kind of weird stuff about quantum mechanics, because he's pulling some of Ruby's memories. This only seems to happen on generation since room id is same.

**Comment by sirkitree** [comment]
Possibly related to #32

**Comment by dreaminglucid** [comment]
will look into this today

**Comment by sirkitree** [comment]
I see this is closed but I think it's still happening

**Comment by lalalune** [comment]
Fixed it
