### ISSUE TITLE
On PNPM Install this happens

### ISSUE THREAD

**Issue by cgallic** [ai16z/eliza#237]
packages/core postinstall$ npx playwright install-deps && npx playwright install
│ Installing dependencies...
│ Switching to root user to install dependencies...
│ Get:1 http://nova.clouds.archive.ubuntu.com/ubuntu lunar InRelease [267 kB]
│ Get:2 http://nova.clouds.archive.ubuntu.com/ubuntu lunar-updates InRelease [109 kB]
│ Get:3 http://nova.clouds.archive.ubuntu.com/ubuntu lunar-backports InRelease [99.9 kB]
│ Hit:4 http://security.ubuntu.com/ubuntu lunar-security InRelease
│ Fetched 475 kB in 1s (421 kB/s)
│ Reading package lists...
│ Reading package lists...
│ Building dependency tree...
│ Reading state information...
│ E: Unable to locate package libasound2t64
│ E: Unable to locate package libatk-bridge2.0-0t64
│ E: Couldn't find any package by glob 'libatk-bridge2.0-0t64'
│ E: Couldn't find any package by regex 'libatk-bridge2.0-0t64'
│ E: Unable to locate package libatk1.0-0t64
│ E: Couldn't find any package by glob 'libatk1.0-0t64'
│ E: Couldn't find any package by regex 'libatk1.0-0t64'
│ E: Unable to locate package libatspi2.0-0t64
│ E: Couldn't find any package by glob 'libatspi2.0-0t64'
│ E: Couldn't find any package by regex 'libatspi2.0-0t64'
│ E: Unable to locate package libcups2t64
│ E: Unable to locate package libglib2.0-0t64
│ E: Couldn't find any package by glob 'libglib2.0-0t64'
│ E: Couldn't find any package by regex 'libglib2.0-0t64'
│ E: Unable to locate package libgtk-3-0t64
│ E: Unable to locate package libicu74
│ E: Unable to locate package libevent-2.1-7t64
│ E: Couldn't find any package by glob 'libevent-2.1-7t64'
│ E: Couldn't find any package by regex 'libevent-2.1-7t64'
│ E: Unable to locate package libpng16-16t64
│ E: Unable to locate package libvpx9
│ Failed to install browser dependencies
│ Error: Installation process exited with code: 100
└─ Failed in 7s at /home/ubuntu/dev/eliza/packages/core
 ELIFECYCLE  Command failed with exit code 1.
 
 
 Getting this error

**Comment by lalalune** [comment]
Try this:
```
sudo apt-get update
sudo apt-get install build-essential
```

Might be some underlying system dependencies You might also need to install `ffmpeg`

**Comment by bathrobe** [comment]
same, the add'l installs don't help. i'm on pop!_os

**Comment by lalalune** [comment]
Error is `npx playwright install-deps && npx playwright install`, I can think of a fix

**Comment by cgallic** [comment]
https://github.com/microsoft/playwright/issues/23296 Think this is it since I was on Ubuntu 23
