### ISSUE TITLE
ai16z.github.io/eliza page doesn't display properly in darkmode

### ISSUE THREAD

**Issue by yodamaster726** [ai16z/eliza#268]
https://ai16z.github.io/eliza page doesn't display properly in darkmode on macos, chrome/safari.  

looks fine when I switch the OS back to light mode.  issue seems to be just on this landing page.

<img width="1429" alt="image" src="https://github.com/user-attachments/assets/45844dfa-53ff-4407-8f23-de14b9ff6715">

**Comment by sirkitree** [comment]
I think @madjin knows about this one already, but thank you for reporting.

**Comment by yodamaster726** [comment]
Verified fix by PR #266 - looks good.   Needs to be deployed to https://ai16z.github.io/eliza/

<img width="1605" alt="image" src="https://github.com/user-attachments/assets/70caf879-ce26-4dd2-aeaa-f37576fc170d">

**Comment by yodamaster726** [comment]
@madjin docs build is broken again - looks like a similar problem from a few days back.

I get a ton of these errors when I run `pnpm run dev` in the docs folder.

![image](https://github.com/user-attachments/assets/4ac90b84-02cd-4a6f-8944-baf12dc5025e)

**Comment by yodamaster726** [comment]
This is what you see on the browser side:
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/cf28e020-b6ce-447c-93c7-6779d37b2a4b">

**Comment by djaramil** [comment]
Looks like it’s fixed again.  I wish that the build didnt update package.json.
