### ISSUE TITLE
inconsistent version of node 

### ISSUE THREAD

**Issue by yodamaster726** [ai16z/eliza#269]
readme says to use 22+ but code is looking for 23.1

<img width="433" alt="image" src="https://github.com/user-attachments/assets/c6e05fc0-a4a9-486a-867a-850b684a45bd">

![image](https://github.com/user-attachments/assets/3afc8bfd-189e-4f7b-bac2-4f1639d4efb2)

![image](https://github.com/user-attachments/assets/8ec145ef-7016-47e6-a9b0-6b8e6380c8e9)

**Comment by madjin** [comment]
![image](https://github.com/user-attachments/assets/95f5e235-e14e-464c-aece-897e338cb3a4)
hesitant to change atm because someone in discord used node 22 for getting things to work
