### ISSUE TITLE
Incorrect steps in readme for starting eliza

### ISSUE THREAD

**Issue by yodamaster726** [ai16z/eliza#270]
Trying the latest code, the Install went good - with 23.1.  However, when following the instructions on how to start it, I ran into an issue.

This part of the online docs says that I start eliza and then start the shell but `pnpm run shell` is not a valid command, nor is it defined in package.json

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/ef3794bb-9b99-41a8-8f16-5f0c71391d50">

**Comment by sirkitree** [comment]
cc @madjin

**Comment by madjin** [comment]
appreciate the tip, new docs coming soon

**Comment by yodamaster726** [comment]
Docs are much better now
