### ISSUE TITLE
unable to run defaultcharacter with ModelProviderName.LLAMACLOUD local

### ISSUE THREAD

**Issue by yodamaster726** [ai16z/eliza#271]
I'm trying to run the latest eliza with the defaultcharacter with the local Ollama.   starts up fine but as soon as I try to interact with it, it crashes saying it can't find the embeddingModel, but that's not the one that's configured as part of LLAMACLOUD

![image](https://github.com/user-attachments/assets/1c9ea2f5-8de2-44a4-ac77-d9c99b6dc03d)

![image](https://github.com/user-attachments/assets/102774c1-c422-4c48-928f-e3f685d00d04)

this is the correct embedding and I have it installed:
![image](https://github.com/user-attachments/assets/2eeba077-2113-42f3-96f8-e39cf84a8bda)

![image](https://github.com/user-attachments/assets/f564efdc-2023-4f32-b433-153b06c44268)

I even configured it in my .env file:
![image](https://github.com/user-attachments/assets/c3be0618-e46e-466c-893c-abab31f92493)

I'm starting at getting things running at the lowest level and then start adding clients one at a time.

It seems like there is something not right in DirectClient, but I can't put my finger on it.  For sure, there seems to be a few other provider related things hardcoded in there.

Let me know if I'm missing something.

**Comment by deepfates** [comment]
I think this is because of the mapping between model names in `modelProvider`. Solved this in my local character file by setting the lowercase version: `"modelProvider": "llama_cloud"`

**Comment by yodamaster726** [comment]
fixed now
