### ISSUE TITLE
advanced usage section of docs doesn't include instructions for memory management

### ISSUE THREAD

**Issue by twilwa** [ai16z/eliza#275]
**Describe the bug**

The docs section simply explains that it has the functionality, it doesn't explain how it works or how to use it

**To Reproduce**

go to the docs and search memory
**Expected behavior**

instructions on how to do memory management
**Screenshots**

![image](https://github.com/user-attachments/assets/23ffc956-fd56-4d46-8608-a806efbb24f9)
![image](https://github.com/user-attachments/assets/80390c52-ad18-4de0-9744-6f994a439fb2)
![image](https://github.com/user-attachments/assets/668bb2da-2f2f-46a2-ba5c-795585679573)

**Additional context**

The example I beleive is correct -- I was searching the docs for how to clear the memory db and rebuild it, and was unable to find the instructions

**Comment by madjin** [comment]
![image](https://github.com/user-attachments/assets/c41c7aaf-39ee-4cc6-ad9e-0e73f01dae9c)
this is from the new docs, hopefully it is a worthy improvement

**Comment by twilwa** [comment]
To some degree -- ideally, there's instructions about how I , as a developer or user, can CRUD memories. That's what I was looking for when I clicked the section
