### ISSUE TITLE
Quickstart guide is missing important info

### ISSUE THREAD

**Issue by TonySimonovsky** [ai16z/eliza#284]
**Describe the bug**

Doc pages:
* https://github.com/ai16z/eliza/blob/main/docs/docs/guides/configuration.md
* https://github.com/ai16z/eliza/blob/main/docs/docs/guides/basic-usage.md

This page a basic setup code but doesn't mention where to put it (folder/filename)

**Comment by odilitime** [comment]
Do you mean for like custom actions, db backends, and advanced config? Because the rest of the config has paths now.

Also basic-usage is gone
