### ISSUE TITLE
pnpm start reports an error and cannot be started. Why is this? I installed it according to the documentation steps.

### ISSUE THREAD

**Issue by zongyanbin** [ai16z/eliza#288]
**Describe the bug**

pnpm start reports an error and cannot be started. Why is this? I installed it according to the documentation steps.

![image](https://github.com/user-attachments/assets/5bc3c344-b921-4931-8d14-f9ca046eaac1)

**To Reproduce**

pnpm i         
pnpm start reports an error and cannot be started. Why is this? I installed it according to the documentation steps.
           

**Expected behavior**

**Screenshots**

**Additional context**

![image](https://github.com/user-attachments/assets/d3aa93b3-e965-4c04-812e-073686775368)

**Comment by leomercier** [comment]
<img width="1144" alt="Screenshot 2024-11-13 at 17 19 31" src="https://github.com/user-attachments/assets/d83a24a0-65e5-433f-a7e2-bea6633e8f64">

Same error on updating too.

**Comment by leomercier** [comment]
Will look again

**Comment by lalalune** [comment]
i think this is fixed
