### ISSUE TITLE
Feature Request: Automated Bot Registry and Private Communication Protocol

### ISSUE THREAD

**Issue by sirkitree** [ai16z/eliza#291]
**Summary**: Implement an automated registry and communication system that enables trading bots to discover each other, communicate efficiently, and trade in a secure and private back channel. 

**Description**:
As the project expands and more instances of the trading bot are forked and installed, there's an opportunity for these bots to be aware of each other's existence and to communicate directly. The goal is to establish a decentralized, automated registry system that allows bots to discover and authenticate each other. Once connected, the bots will communicate through a private back channel to exchange data and execute trades efficiently.

**Proposed Features**:

1. **Automated Registry System**: 
   - Each bot will register itself in a decentralized registry (e.g., using a lightweight P2P network or distributed ledger technology).
   - Bots will periodically update the registry, checking for new bots or changes in status.
   - The registry will include basic metadata to facilitate discovery, like cryptographic keys for authentication.
   - Possibly services a particular bot provides to other bots that they could pay for in the future. (more on this later)

2. **Private Back Channel Communication**:
   - Implement a secure, real-time communication protocol, potentially leveraging WebRTC or a similar P2P technology.
   - The protocol should ensure encrypted communication between bots, minimizing the risk of interception.
   - Messages will be designed for minimal latency, suitable for rapid data exchange and trading negotiations.

3. **Authentication and Security**:
   - Use public-private key cryptography for bot authentication, ensuring only legitimate bots can participate in the network.
   - Establish rules for trust and security, with mechanisms to handle untrusted or malicious bots.

4. **Efficient Trading Protocol**:
   - Design a protocol that allows bots to share and match order books in a streamlined manner.
   - Ensure trades are executed quickly, with minimal delay, using predefined negotiation rules.
   - Incorporate a fallback mechanism if communication or negotiation fails.

**Benefits**:
- **Speed**: A dedicated, private communication channel will facilitate faster data exchange compared to public platforms.
- **Security**: Encrypted communication ensures that sensitive trading data remains confidential.
- **Scalability**: The decentralized nature of the registry will support the growth of the network without becoming a bottleneck.

**Considerations**:
- The system should be resilient to potential attacks, like Sybil attacks, by incorporating strong authentication and trust mechanisms.
- Developing a lightweight and efficient protocol is critical to minimize resource usage and latency.

**Comment by lalalune** [comment]
Vehemently against private communication protocols between agents of any sort. Critical to agent-human alignment that they use social media as the basis for communication and memory. Bot registry is I think not a telemetry we want.

Have a solution for this that is more in line with our moral values-- I know this seems small, but it is extremely, extremely important that we make the bots use human communication and human tools at all times.
