### ISSUE TITLE
Docs improvements bounty ideas

### ISSUE THREAD

**Issue by madjin** [ai16z/eliza#298]
- read more = broken link: https://ai16z.github.io/eliza/docs/community/stream-notes/
- readme is outdated
- pnpm run shell not valid
- go through and test the docs to be valid
- add jsdocs comments to all the code
- add links to the code in code snippet examples
- check and fix all the issues in github

will add more things to fix for a bounty on https://ai16z.github.io/

**Comment by CHASERS12** [comment]
When trying to run your custom character in dev mode - pnpm run dev - you need to *pin character to dev shell script

**Comment by odilitime** [comment]
First bullet point is now addressed at https://github.com/ai16z/eliza/commit/951aa3eb8b262b54419b4b3b8ccfd1358ef3ec25 #321 just noting it so others don't attempt it
