### ISSUE TITLE
Farcaster Client / Plugin

### ISSUE THREAD

**Issue by madjin** [ai16z/eliza#300]
Parity with Twitter client, but on Farcaster

Reward: $1000 USD in $ai16z + $1000 USD in $degenai

As seen on https://ai16z.github.io/

**Comment by rubinovitz** [comment]
Do you mean you want a Twitter clone or that you want Eliza to be able to have its existing Twitter bot functionality Farcaster?

**Comment by lalalune** [comment]
I mean that we want the same functionality in Farcaster

**Comment by nutbox-io** [comment]
We have created a 'social oracle' between Twitter and Steem/Farcaster, which already supports the Steem Blockchain, and we are planning to support Farcaster Hubs. Our idea is that Twitter serves as the operations dashboard for on-chain activities, while Steem/Farcaster acts as the Social DA. I wonder if you might be interested in this.

You can try it out here: tiptag.social. Tweet and add #TipTag #Slime, and the content will be sync to Slime Community（on-chain community）.
