### ISSUE TITLE
EVM Integration

### ISSUE THREAD

**Issue by madjin** [ai16z/eliza#303]
EVM Integration

- Integrate Ethereum wallet and demonstrate Eth L1 and Base L2
- Copy and paste solana plugin and recreate with EVM
- Swapping action, wallet provider

Reward: $1500 USD in $degenai as seen on https://ai16z.github.io/

**Comment by leonprou** [comment]
Gm @madjin 
would love to work on this one.

Couple of questions and remarks:
- Just need to figure our which services we want to use in Base/ETH. I suggest Aerodrome/Uniswap, but maybe using li.fi/enso/0x scales better.
- What's good alternative for pump.fun on Base/Ethereum?
