### ISSUE TITLE
New Plugin Idea: log discord and summarize channels

### ISSUE THREAD

**Issue by sirkitree** [ai16z/eliza#318]
**Is your feature request related to a problem? Please describe.**

We could use a way to summarize discord channels periodically. There's too much activity to keep up on, but a periodic (like daily or weekly) summary would help us to keep up as a community.

**Describe the solution you'd like**

Create a new plugin for eliza that would log particular channels in a discord and save the logs or into memory. Then periodically summarize these and post to a different channel. i.e. if logging `#arena` post daily summaries to `#area-summary`.

**Describe alternatives you've considered**

Doing this manually.

**Comment by MeDott29** [comment]
I was made for this.

**Comment by MeDott29** [comment]
Can I lock this bounty?

**Comment by madjin** [comment]
> Can I lock this bounty?

hop into ai16z discord: https://discord.gg/YQXh2xYV

tag me, lets discuss

**Comment by Myestery** [comment]
Hello @madjin, I'm interested in this also
What channel can I reach you in the discord?

**Comment by lalalune** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> We could use a way to summarize discord channels periodically. There's too much activity to keep up on, but a periodic (like daily or weekly) summary would help us to keep up as a community.
> 
> **Describe the solution you'd like**
> 
> Create a new plugin for eliza that would log particular channels in a discord and save the logs or into memory. Then periodically summarize these and post to a different channel. i.e. if logging `#arena` post daily summaries to `#area-summary`.
> 
> **Describe alternatives you've considered**
> 
> Doing this manually.

this already exists. you should be able to ask for a channel summary for any given date range. it attaches as a markdown.
