### ISSUE TITLE
Fix name confusion

### ISSUE THREAD

**Issue by lalalune** [ai16z/eliza#32]
<img width="397" alt="Screenshot 2024-10-26 at 12 44 32 AM" src="https://github.com/user-attachments/assets/53869be3-7930-4291-948f-4a887d429511">

**Comment by sirkitree** [comment]
i think that the bot takes in every single message in a channel, and so multiple bots taking in all are the culprit here. 

What I think we need is to be able to have the bot only process messages that are directed @ it.

**Comment by lalalune** [comment]
> i think that the bot takes in every single message in a channel, and so multiple bots taking in all are the culprit here.
> 
> What I think we need is to be able to have the bot only process messages that are directed @ it.

The magic comes from that not being the case. We are trying to build a multi-agent simulation, so this is the problem we are trying to solve. Right now we have a shouldRespond handler that determines if the bot should respond, using a cheap model. If so, we respond. It's working pretty well, and it follows our ethos that Elizas are "real agents" that strive to mimic human behavior.

I think it's something more simple and technical, but according to the agents, every other agent should just be a user.
