### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by lalalune** [ai16z/eliza#34]
well, we had docs before:
https://github.com/JoinTheAlliance/bgent/tree/main/docs

We if add claude comments to all of our files with tsdoc, we can export everything into an api documentation nicely.

So let's migrate everything and set that back up.

**Comment by sirkitree** [comment]
Looking for some history on this... Is bgent eliza's predecessor? is all of that documentation relevant here?

**Comment by sirkitree** [comment]
added in https://github.com/ai16z/eliza/commit/ab84bf09791c9a793c5ccb648ecd82918d838af6
