### ISSUE TITLE
build.sh crash

### ISSUE THREAD

**Issue by denizekiz** [ai16z/eliza#379]
**Describe the bug**

build.sh doesn't work in Windows due to usage of "cut" for node version check. We need a cross-platform solution for checking node.js, or just remove node.js version check.
**To Reproduce**

build.sh

**Comment by whonion** [comment]
`Note for Windows Users: WSL is required`

**Comment by sirkitree** [comment]
i just ran this in PS fine

hash: a2e0954a5871eaace15dc9197fd7457b1b62064e from main
no. just main branch, node v23.1.0, pnpm clean, pnpm install, pnpm build, pnpm start --character=(file)

**Comment by denizekiz** [comment]
WSL 2 installing instructions added for windows users to readme.md
https://github.com/ai16z/eliza/pull/419
