### ISSUE TITLE
using Groq API (or RedPill or Google Gen AI) as model provider

### ISSUE THREAD

**Issue by YoungPhlo** [ai16z/eliza#422]
**Describe the bug**

trying to use the **Groq API** but its not clear how to define the model in the .env file. 
other providers have `SMALL_HEURIST_LANGUAGE_MODEL`, `SMALL_HEURIST_LANGUAGE_MODEL`, etc

I'm not sure how to define the model in the .env file

**To Reproduce**

https://github.com/ai16z/eliza/blob/main/.env.example

**Expected behavior**

Something similar to Heurist
`SMALL_GROQ_LANGUAGE_MODEL=`
`MEDIUM_GROQ_LANGUAGE_MODEL=`
`LARGE_GROQ_LANGUAGE_MODEL=`

**Additional context**
If not custom `.env` variables at least a nod in the right direction
my IDE pointed me to `packages/core/src/models.ts`

**Comment by manishbyatroy** [comment]
Why not use Heurist? heurist.ai/dev-access use access code 'ai16z' to get instant api approval! Use a proper email as it emails you the api key.

**Comment by YoungPhlo** [comment]
> They're fixing this In the meantime Why not use Heurist? https://heurist.ai/dev-access use access code 'ai16z' to get instant api approval! Use a proper email as it emails you the api key.

Personally love using Heurist but I think it's a good idea to have back up providers. Heurist might not be able to provide free inference forever. Nice while it lasts though :)
