### ISSUE TITLE
Commands for starting agents without character profiles

### ISSUE THREAD

**Issue by sirkitree** [ai16z/eliza#47]
In the package.json there are scripted commands for agents like ruby and spartan, but we do not have their character profiles in `/characters`

I propose we either:
1. remove the commands from package.json, or
2. (preferred) add the character profiles for them

```
    "start:service:ruby": "pm2 start npm --name=\"ruby\" --restart-delay=3000 --max-restarts=10 -- run start:ruby",
    "stop:service:ruby": "pm2 stop ruby",
    "start:ruby": "node --loader ts-node/esm src/index.ts --characters=\"characters/ruby.character.json\"",
    ...
    "start:service:degen": "pm2 start npm --name=\"degen\" --restart-delay=3000 --max-restarts=10 -- run start:degen",
    "stop:service:degen": "pm2 stop degen",
    "start:degen": "node --loader ts-node/esm src/index.ts --characters=\"characters/degenspartan.json\"",
```    

Thoughts?

**Comment by adnanmirza1** [comment]
Hello @sirkitree, hope you'll be fine. Sorry for being off the topic but I need help setting up this project on my linux machine, I added env's, node v 20.13.1, runned npm i which was successful, and now after node --loader ts-node/esm src/index.ts
I'm seeing below error.
![image](https://github.com/user-attachments/assets/a2a66842-a961-4a46-baa4-ac564609eb87)

I'll appreciate any of your help. Thank you.

**Comment by sirkitree** [comment]
>  Sorry for being off the topic

Indeed. Please open a new issue when you have such a thing, and we can help you there. I've opened a new one for you here: #76
