### ISSUE TITLE
🤖 Confidence Level Implementation

### ISSUE THREAD

**Issue by sirkitree** [ai16z/eliza#50]
🎯 Confidence Metrics: Establishing clear confidence levels for trades helps in assessing the reliability of recommendations, making it easier to identify which trades are worth pursuing based on user input.

Implement a confidence level system for order evaluation with low, medium, and high confidence categories.

#### Requirements
- Define criteria for each confidence level
- Create UI elements for confidence selection
- Implement confidence scoring algorithm
- Add confidence level filters to order book

#### Acceptance Criteria
- [ ] Users can assign confidence levels to orders
- [ ] Confidence levels are clearly displayed in the UI
- [ ] Filtering system works based on confidence levels
- [ ] Confidence scoring affects trust calculations

**Comment by lalalune** [comment]
@MarcoMandar has been working on this. The order book and trust system are unified, so I am assigning tickets which we can deem duplicate and close as necessary.
