### ISSUE TITLE
Non node.js environments have issues building (workers for instance)

### ISSUE THREAD

**Issue by antpb** [ai16z/eliza#507]
**Describe the bug**

Non node.js environments may have issues building because of some packages and how they are imported. 

**To Reproduce**

Make a worker, include eliza/core and attempt to build. It will throw an error similar to 

```
  ✘ [ERROR] No loader is configured for ".node" files:
  node_modules/@anush008/tokenizers-darwin-universal/tokenizers.darwin-universal.node

      node_modules/@anush008/tokenizers/index.js:116:32:
        116 │ ... nativeBinding = require('@anush008/tokenizers-darwin-universal')
 ```

**Expected behavior**

Build successful

**Screenshots**

<img width="666" alt="image" src="https://github.com/user-attachments/assets/00c09f9b-0ea2-4fd9-8330-e6083ec180d8">

PR incoming

**Comment by AndonMitev** [comment]
Is this released, I'm still experiencing same issue 

```
"next": "15.0.3",
"@ai16z/adapter-supabase": "0.1.4-alpha.3",
"@ai16z/eliza": "0.1.4-alpha.3",
```
