### ISSUE TITLE
create-eliza-app package doesn't install or exist

### ISSUE THREAD

**Issue by yodamaster726** [ai16z/eliza#553]
**create-eliza-app package in the packages directory doesn't work**

Following the readme in the package in `repo-folder/packages/create-eliza-app/` fails.

![image](https://github.com/user-attachments/assets/85b314f4-f92e-4611-b744-2a7b82de5f3c)

Is this package still valid ?  I see something else on the ai16z website.

![image](https://github.com/user-attachments/assets/05d70955-5bcd-4f27-b42b-30d4935d2304)

**Comment by awidearray** [comment]
@shakkernerd
