### ISSUE TITLE
Renovate bot for automated updates on dependencies

### ISSUE THREAD

**Issue by sirkitree** [ai16z/eliza#58]
I think it would be beneficial to add Renovate Bot to automate dependency updates. 

Renovate Bot automatically manages your Node.js dependencies by scanning your repository and creating pull requests for available [updates](https://www.augmentedmind.de/2023/07/30/renovate-bot-introduction/). This automation provides several crucial advantages:

**Risk Reduction**
- Updates are delivered in small, manageable increments rather than large, risky batch updates
- Each update comes with its own [pull request](https://senacor.blog/how-to-renovate-why-and-how-you-should-use-automated-dependency-updates-in-your-software-projects/), making it easier to identify breaking changes
- Security vulnerabilities are addressed more quickly through timely updates

**Time Savings**
- Eliminates manual dependency checking and updating
- Provides transparency into outdated dependencies without manual tracking
- Automatically creates pull requests with changelog information included

**Flexible Configuration**
- Supports automatic merging of updates that pass tests
- Allows grouping of updates to r[educe PR noise](https://docs.renovatebot.com/getting-started/use-cases/)
- Can schedule updates during off-hours to avoid CI resource contention

**Comment by mrdavidburns** [comment]
I see the branch was merged. To make it work a repo admin will need to add it from the Marketplace.
https://github.com/apps/renovate

**Comment by sirkitree** [comment]
![image](https://github.com/user-attachments/assets/4b83aab3-28f1-422f-9eb6-161d2248b5f9)

Anything else to do here?

**Comment by mrdavidburns** [comment]
Go here https://developer.mend.io/github/ai16z/eliza
Click `Settings`
That should get you to this page -> https://developer.mend.io/github/ai16z/eliza/-/settings
Then click `Dependencies`.

Set the options to be like this and then click `Save`:
![image](https://github.com/user-attachments/assets/b4f90e72-327a-4071-9ed5-209ccdf7aa4d)

**Comment by mrdavidburns** [comment]
Don't close this issue. This is where you can track updates, manually trigger a PR to build or rebase.
- https://github.com/ai16z/eliza/issues/79

**Comment by sirkitree** [comment]
This worked well. I was able to get all dependencies updates and will keep that issue open.
