### ISSUE TITLE
Cannot find module '@ai16z/eliza' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Howard0x3f** [ai16z/eliza#601]
Environment：
WSL2 : Ubuntu-20.04
Nodejs:v23.1
pnpm:9.14.2
git checkout v0.1.3
When I run `pnpm install`, no errors occur.  
However, when I run `pnpm start --character="characters/trump.character.json"`, an issue arises.
 pnpm --filter "@ai16z/agent" start --isRoot "--character=characters/trump.character.json"

> @ai16z/agent@0.0.1 start /home/workspace/eliza/agent
> tsc && node --loader ts-node/esm src/index.ts "--isRoot" "--character=characters/trump.character.json"

src/character.ts:1:64 - error TS2307: Cannot find module '@ai16z/eliza' or its corresponding type declarations.

1 import { Character, ModelProviderName, defaultCharacter } from "@ai16z/eliza";
                                                                 ~~~~~~~~~~~~~~

src/index.ts:1:41 - error TS2307: Cannot find module '@ai16z/adapter-postgres' or its corresponding type declarations.

1 import { PostgresDatabaseAdapter } from "@ai16z/adapter-postgres";
**Describe the bug**

**Comment by yodamaster726** [comment]
I’ve run I to this issue as well.  I have a fix coming for it. 

Workaround is to put ../ in front of characters.  ie. ../characters/trump.character.json

**Comment by Howard0x3f** [comment]
> I’ve run I to this issue as well. I have a fix coming for it.
> 
> Workaround is to put ../ in front of characters. ie. ../characters/trump.character.json

I changed the command to pnpm start --character="../characters/trump.character.json", but the same error still occurs.

**Comment by Howard0x3f** [comment]
![image](https://github.com/user-attachments/assets/7f42e0e5-ecd3-433b-8406-bd4e233af0d6)
In my VSCode, it shows that @ai16z/ cannot be found.

**Comment by milezzz** [comment]
Glad I'm not the only one. Exact same issue on a fresh Debian 12.

**Comment by djaramil** [comment]
> ![image](https://private-user-images.githubusercontent.com/72191622/389792739-7f42e0e5-ecd3-433b-8406-bd4e233af0d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDc3NTIsIm5iZiI6MTczMjY0NzQ1MiwicGF0aCI6Ii83MjE5MTYyMi8zODk3OTI3MzktN2Y0MmUwZTUtZWNkMy00MzNiLTg0MDYtYmQ0ZTIzM2FmMGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE4NTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMDA4ODYzNjUwZjIyZjFkNGUwYmQyOGJhZjE0Y2JmNGViOTMxMmI1Njg3NTA3ZDE4MzNmMTU0NmMxYTIzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vXASMCNmeAvckMl11nJ-lS_mcEvxI02F--uEe0t26ho) In my VSCode, it shows that @ai16z/ cannot be found.

Did my work around help you to run the character ?  I'm assuming you did the pnpm install and then the pnpm build, right ?

**Comment by djaramil** [comment]
> Glad I'm not the only one. Exact same issue on a fresh Debian 12.
> 
> EDIT: Solved by doing a `pnpm build` after `pnpm i`
> 
> ...At least the character builds but now I have a new error: `[Used disallowed intents](error: new Error("Used disallowed intents"))` - looks like something I have to do with my discord bot.
> 
> EDIT #2: Fixed the intents error above by switching these 3 toggles in Discord Dev Portal. Bot seems to work now.
> 
> ![](https://camo.githubusercontent.com/bc320bfcb8b037f226daa2f2cf649a96199bfc2de83d196648e405052aefb23d/68747470733a2f2f692e696d6775722e636f6d2f326539693044512e706e67)

I'm on the same path as you here - we need to get these details in the documentation.  I would love to share notes with you on this.

**Comment by milezzz** [comment]
> Did my work around help you to run the character ? I'm assuming you did the pnpm install and then the pnpm build, right ?

correct, working now and posting to discord...will try Telegram and image gen next

**Comment by yodamaster726** [comment]
> Glad I'm not the only one. Exact same issue on a fresh Debian 12. 
> 
> 
> 
> EDIT: Solved by doing a ```pnpm build``` after ```pnpm i``` 
> 
> 
> 
> ...At least the character builds but now I have a new error:  ```[Used disallowed intents](error: new Error("Used disallowed intents"))``` - looks like something I have to do with my discord bot.
> 
> 
> 
> EDIT #2:  Fixed the intents error above by switching these 3 toggles in Discord Dev Portal. Bot seems to work now. 
> 
> 
> 
> ![](https://i.imgur.com/2e9i0DQ.png)

Would love to connect with you on discord.  I'm on a similar path and want to capture any documentation items that we should capture.  

My discord id is yoda26.  Can you dm me back. I'll delete this message afterwards.

**Comment by yodamaster726** [comment]
> > I’ve run I to this issue as well. I have a fix coming for it.
> > Workaround is to put ../ in front of characters. ie. ../characters/trump.character.json
> 
> I changed the command to pnpm start --character="../characters/trump.character.json", but the same error still occurs.

I believe this gets resolved if you do `pnpm build` and then you do the `pnpm start`

**Comment by lalalune** [comment]
It does but that sucks, need to use turborepo
