### ISSUE TITLE
Optional image model provider to character and runtime

### ISSUE THREAD

**Issue by yoniebans** [ai16z/eliza#647]
**Is your feature request related to a problem? Please describe.**

Currently, users can only select a single model provider for both text and image generation. This becomes limiting when a provider excels at text generation but offers subpar image generation capabilities, or vice versa.

**Describe the solution you'd like**

We propose adding an optional image model provider setting that would take precedence over the default model provider when configured. If no image provider is specified, the system would continue using the default model provider, maintaining backward compatibility.

**Describe alternatives you've considered**

We've explored using a single provider (such as Heurist or OpenAI) for both text and image generation. While this works adequately, it limits flexibility. For instance, if you want to use a fine-tuned model from a specialized image generation service, this isn't currently possible.

**Additional context**

I've implemented a similar solution that allows me to use OpenAI for text generation while leveraging a custom fine-tuned model on fal.ai for image generation.

**Comment by 0xTomDaniel** [comment]
Added in #491
