### ISSUE TITLE
fal.ai image generation

### ISSUE THREAD

**Issue by yoniebans** [ai16z/eliza#648]
**Is your feature request related to a problem? Please describe.**

Currently there is no native integration for fal.ai image generation models. Users wanting to leverage fal.ai's specialized image models need to implement custom solutions.

**Describe the solution you'd like**

Add built-in support for fal.ai image generation models, allowing users to specify their fal.ai API key and lora path (if they have one). This would enable direct access to fal.ai's models through the existing image generation interface.

**Describe alternatives you've considered**

Using other supported providers already in codebase

**Additional context**

Native integration would benefit users wanting more control over the image generation capabilities.

**Comment by tsubasakong** [comment]
Heurist has the powerful image generation models (FLUX, Stable Diffusion, and loras) too, and already exist inside the eliza. Apply the API key [here](https://dev-api-form.heurist.ai/) with referral code `ai16z` to get the key immediately.   

You can try the image generation web (https://imagine.heurist.ai/). The images are amazing!
