### ISSUE TITLE
Twitter client only works for one agent when running multiple agents simultaneously

### ISSUE THREAD

**Issue by ccerrato147** [ai16z/eliza#656]
**Describe the bug**

Eliza has the capability to run multiple agents at once. They each should be able to use the twitter credentials that they're given. Right now the system only runs the twitter client for one of the agents.

**To Reproduce**

1. Provide multiple characters to the Eliza framework to run in parallel.
2. Monitor the two twitter accounts that you assigned to them for new posts
3. Only one of the accounts will show new posts.

**Expected behavior**

All the twitter accounts given the multiple agents should have new posts from said agents not just one.

**Comment by lalalune** [comment]
Yeah. We need to solve this.

**Comment by BalanaguYashwanth** [comment]
Is this issue resolved ?

**Comment by BalanaguYashwanth** [comment]
@lalalune review and let me know,

**Comment by tcm390** [comment]
> Is this issue resolved ?

Yes, the issue has been resolved.

I just checked out the latest develop branch and tested running two accounts in parallel. Both responded to me as expected. Could you please confirm?

<img width="607" alt="Screenshot 2024-12-13 at 11 42 37 AM" src="https://github.com/user-attachments/assets/0f803786-4acf-4d92-a3eb-ef35252d5428" />

<img width="587" alt="Screenshot 2024-12-13 at 11 43 16 AM" src="https://github.com/user-attachments/assets/b5e6b930-474a-45c0-81c5-c23e1906e0c9" />

<img width="613" alt="Screenshot 2024-12-13 at 11 43 00 AM" src="https://github.com/user-attachments/assets/871ee56b-5056-4471-8250-348f05a0a6cc" />

**Comment by BalanaguYashwanth** [comment]
Have a doubt, how you are loading two different twitter account credential's ?

If you hard code -
```
const username = this.runtime.getSetting("TWITTER_USERNAME");
```
Reference -

<img width="655" alt="image" src="https://github.com/user-attachments/assets/81fd64a0-516b-4e1f-a32b-6241e87ef787" />

**Comment by tcm390** [comment]
> @tcm390 Have a doubt, how you are loading two different twitter account credential's ?
> 
> If you hard code -
> 
> ```
> const username = this.runtime.getSetting("TWITTER_USERNAME");
> ```
> 
> Reference -
> 
> <img alt="image" width="655" src="https://private-user-images.githubusercontent.com/36238382/395640579-81fd64a0-516b-4e1f-a32b-6241e87ef787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMTAxMjQsIm5iZiI6MTczNDEwOTgyNCwicGF0aCI6Ii8zNjIzODM4Mi8zOTU2NDA1NzktODFmZDY0YTAtNTE2Yi00ZTFmLWEzMmItNjI0MWU4N2VmNzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDE3MTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZGViYTAzN2FjZmQ5MTY3NjM5OTg2NmZlOWJkZWIxMjliODM3YTlmMTAyYjg3OWE4YjM4OWZiM2EwMDMxNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MER52KLIoIHsOPgMlindQZOpFRcniXFE9RFImtK2hNM">

oh you need to set secret/settings in character file like this:
(getSetting would check the character secret first: https://ai16z.github.io/eliza/docs/guides/secrets-management/)

"name": "Eliza",
    "clients": ["twitter"],
    "plugins": [],
    "modelProvider": "openai",
    "settings": {
        "secrets": {
            "TWITTER_USERNAME": "XXXX",
            "TWITTER_PASSWORD": "XXXXX",
            "TWITTER_EMAIL": "XXXXXXX"
        },
        "voice": {
            "model": "en_US-hfc_female-medium"
        }
    },

**Comment by BalanaguYashwanth** [comment]
@tcm390 I didn't know it can be possible in this way, then can you please close this PR,

 so that dev's can focus on other open PR's

**Comment by tcm390** [comment]
sure :)
