### ISSUE TITLE
Twitter Client Breaks out of the box

### ISSUE THREAD

**Issue by toddokuhawado** [ai16z/eliza#673]
Hello, 

I'm working on a fresh install on a Mac. I cannot get the twitter client to work no matter what I try. I've added 'twitter' to the client list, loaded my credentials in environment variables, but I still receive the following error every time I run it with the twitter credential added: 

```
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @ai16z/agent@0.0.1 start: `tsc && node --loader ts-node/esm src/index.ts "--isRoot" "--character=characters/tate.character.json"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by leonzijun** [comment]
i think the localport3000 have been used it. need kill the pid and restart
