### ISSUE TITLE
Execution gets stuck in a loop

### ISSUE THREAD

**Issue by docherty** [ai16z/eliza#70]
My agent has been getting caught in an random loop where this is included in the terminal output:
```
parsedContent is null
parsedContent is null, retrying
```
The request body is the usual size and headers are as expected, I can't see what the issue is and what repro steps there are. I'm only running text interaction on Discord.

If I get more insight I'll update it here.

**Comment by lalalune** [comment]
Hmmm, hmu on discord (new.moon) and lets fix it.

**Comment by St4rgarden** [comment]
I have run into this a few times as well.
