### ISSUE TITLE
pnpm install error - ELIFECYCLE Exit code 1

### ISSUE THREAD

**Issue by MuhovTheDev** [ai16z/eliza#720]
Specs: Windows11
node 23.1.0

git clone done successfully
git checkout done successfully

got this error at pnpm install:

PS C:\Users\muhov\eliza> pnpm i  
Scope: all 23 workspace projects
 WARN  There are cyclic workspace dependencies: C:\Users\muhov\eliza\packages\adapter-sqlite, C:\Users\muhov\eliza\packages\core
Lockfile is up to date, resolution step is skipped
Packages: +3405
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
Progress: resolved 0, reused 3000, downloaded 0, added 3405, done
node_modules/canvas: Running install script...
node_modules/@discordjs/opus: Running install script, failed in 9.5s
node_modules/@discordjs/opus install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@0.4.5
│ node-pre-gyp info using node@23.1.0 | win32 | x64
│ (node:18700) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ node-pre-gyp info check checked for "C:\Users\muhov\eliza\node_modules\@discordjs\opus\prebuild\node-v131-napi-v3-win32-x64-unknown-unknown\o…  
│ node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-napi-v3-win32-x64-unknown-unknown.tar.…  
│ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131-n…  
│ node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.9.0 and node@23.1.0 (node-v131 ABI, unknown) (falling back to sour…  
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.9.0/opus-v0.9.0-node-v131…  
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@10.2.0
│ gyp info using node@23.1.0 | win32 | x64
│ gyp info ok
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@10.2.0
│ gyp info using node@23.1.0 | win32 | x64
│ gyp info find Python using Python version 3.13.0 found at "C:\Users\muhov\AppData\Local\Programs\Python\Python313\python.exe"
│ gyp ERR! find VS
│ gyp ERR! find VS msvs_version not set from command line or npm config
│ gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
│ gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
│ gyp ERR! find VS
│ gyp ERR! find VS Failure details: undefined
│ gyp ERR! find VS checking VS2019 (16.11.35425.106) found at:
│ gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
│ gyp ERR! find VS - found "Visual Studio C++ core features"
│ gyp ERR! find VS - missing any VC++ toolset
│ gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
│ gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
│ gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
│ gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
│ gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
│ gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
│ gyp ERR! find VS
│ gyp ERR! find VS **************************************************************
│ gyp ERR! find VS You need to install the latest version of Visual Studio
│ gyp ERR! find VS including the "Desktop development with C++" workload.
│ gyp ERR! find VS For more information consult the documentation at:
│ gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
│ gyp ERR! find VS **************************************************************
│ gyp ERR! find VS
│ gyp ERR! configure error
│ gyp ERR! stack Error: Could not find any Visual Studio installation to use
│ gyp ERR! stack at VisualStudioFinder.fail (C:\Users\muhov\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstu…  
│ gyp ERR! stack at VisualStudioFinder.findVisualStudio (C:\Users\muhov\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\fi…  
│ gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
│ gyp ERR! stack at async createBuildDir (C:\Users\muhov\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\configure.js:112:…  
│ gyp ERR! stack at async run (C:\Users\muhov\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js:81:18)
│ gyp ERR! System Windows_NT 10.0.22631
│ gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\muhov\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node…  
│ gyp ERR! cwd C:\Users\muhov\eliza\node_modules\@discordjs\opus
│ gyp ERR! node -v v23.1.0
│ gyp ERR! node-gyp -v v10.2.0
│ gyp ERR! not ok
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\muhov\AppData\Roaming\npm\node_modules\pnpm\dist\…  
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\muhov\eliza\node_modules\@discordjs\node-pre-gyp\lib\util\compile.js:85:20)   
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:507:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1101:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
│ node-pre-gyp ERR! System Windows_NT 10.0.22631
│ node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\muhov\\eliza\\node_modules\\@discordjs\\node-pre-gyp\\bin\\node-p…  
│ node-pre-gyp ERR! cwd C:\Users\muhov\eliza\node_modules\@discordjs\opus
node_modules/canvas: Running install script, failed in 9.6s (skipped as optional)
│ node-pre-gyp ERR! node-pre-gyp -v v0.4.5
│ node-pre-gyp ERR! not ok
│ Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\muhov\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-…  
└─ Failed in 9.5s at C:\Users\muhov\eliza\node_modules\@discordjs\opus
 ELIFECYCLE  Command failed with exit code 1.

**Comment by MuhovTheDev** [comment]
Install Visual C++ Build Environment: [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) (using "Visual C++ build tools" workload) solved the problem 

https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules

**Comment by cxp-13** [comment]
> Install Visual C++ Build Environment: [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) (using "Visual C++ build tools" workload) solved the problem
> 
> https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules

HI，are you successful running? i stuck on WSL and Windows, I need your help if your want.
