### ISSUE TITLE
`pnpm run dev` does not work out of the box

### ISSUE THREAD

**Issue by lalalune** [ai16z/eliza#780]
Right now, `pnpm run dev` is not working properly with turbo.

What we want is for dev to start all packages in watch mode with turbo so that the monorepo can automatically update dependencies downstream while developing, i.e. a watch mode that doesn't require a rebuild.

**Comment by fabianhug** [comment]
check this, I've found some type error in the postgres adapter, but am not sure if I mixed up something on my end:

https://github.com/ai16z/eliza/pull/788 

@lalalune

**Comment by Hdpbilly** [comment]
> check this, I've found some type error in the postgres adapter, but am not sure if I mixed up something on my end:
> 
> #788
> 
> @lalalune

I believe it is due to improper usage of the plpgsql function get_embedding_dimension() which is attempting to use dynamic type modifier. 

Particularly in the postgres schemaL
```
CREATE OR REPLACE FUNCTION get_embedding_dimension()
RETURNS INTEGER AS $$
BEGIN
    -- Check for OpenAI first
    IF current_setting('app.use_openai_embedding', TRUE) = 'true' THEN
        RETURN 1536;  -- OpenAI dimension
    -- Then check for Ollama
    ELSIF current_setting('app.use_ollama_embedding', TRUE) = 'true' THEN
        RETURN 1024;  -- Ollama mxbai-embed-large dimension
    ELSE
        RETURN 384;   -- BGE/Other embedding dimension
    END IF;
END;
$$ LANGUAGE plpgsql;
```

**Comment by hamedf62** [comment]
> > check this, I've found some type error in the postgres adapter, but am not sure if I mixed up something on my end:
> > #788
> > @lalalune
> 
> I believe it is due to improper usage of the plpgsql function get_embedding_dimension() which is attempting to use dynamic type modifier.
> 
> Particularly in the postgres schemaL
> 
> ```
> CREATE OR REPLACE FUNCTION get_embedding_dimension()
> RETURNS INTEGER AS $$
> BEGIN
>     -- Check for OpenAI first
>     IF current_setting('app.use_openai_embedding', TRUE) = 'true' THEN
>         RETURN 1536;  -- OpenAI dimension
>     -- Then check for Ollama
>     ELSIF current_setting('app.use_ollama_embedding', TRUE) = 'true' THEN
>         RETURN 1024;  -- Ollama mxbai-embed-large dimension
>     ELSE
>         RETURN 384;   -- BGE/Other embedding dimension
>     END IF;
> END;
> $$ LANGUAGE plpgsql;
> ```

this is the critical issue would be solve as pgsql doesn't accept dynamic modifiers.

as i checked in supabase you have define 3 different memories table for different embedding dimensions, and same required in PostgreSQL.
