### ISSUE TITLE
Feature Request: Add Aptos and Move Support to the Eliza Framework for Autonomous Agents

### ISSUE THREAD

**Issue by obsrvgmi** [ai16z/eliza#790]
We're building an **Autonomous Agent** using the Eliza Framework on Aptos.
Right now, Eliza doesn’t offer features specific to Aptos, like **wallet creation, trading,** or other opportunities available on Aptos.
We’d love to help by adding support for Aptos or Move to Eliza.
Describe the solution you'd like
We’d love to add an Aptos plugin to Eliza for wallet creation without human involvement, trading, and other features.
We’re big believers in open source and are excited to contribute by adding Aptos Move support to Eliza!"

**Comment by asianviking** [comment]
#818
