### ISSUE TITLE
Characters Do Not Actually Use ExamplePost or ExampleMessage

### ISSUE THREAD

**Issue by toddokuhawado** [ai16z/eliza#791]
You are able to define example posts and messages in the character files, but the characters do not actually receive these in their prompt. I checked this by logging context in the generate text script, and saw that none of these examples are even included in the info sent to the agent, so it is very hard to get unique behaviors that aren't highly generic. Has anyone found a fix for this? It seems like an issue that should be fixed before more features get added.

**Comment by tcm390** [comment]
Thanks for reporting this! Could you provide more details about the issue? For example, a screenshot or steps to reproduce it would be really helpful. On my side, I can see the example messages in the prompt, so any additional context would be great for troubleshooting.

**Comment by augchan42** [comment]
there's two tiers of response handling - first is gating (whether to respond at all) and then if the agent chooses to respond, the full context is loaded.  So watch where you are checking for the context.
