### ISSUE TITLE
Add AI Code Reviewing application from GitHub Marketplace

### ISSUE THREAD

**Issue by mrdavidburns** [ai16z/eliza#81]
**Is your feature request related to a problem? Please describe.**
Looking to increase code quality and efficiency. 

**Describe the solution you'd like**

I would like to propose integrating [CodeFactor](https://github.com/marketplace/codefactor) into this repository to enhance code quality and streamline the review process. CodeFactor offers an automated code review solution that continuously analyzes the repository for potential code issues, ensuring consistent code standards across contributions. Best of all it is FREE for public repositories like this one.

Benefits of Adding CodeFactor:

1.	Automated Code Review: CodeFactor automatically reviews new pull requests and commits, highlighting potential code smells, bugs, and areas for improvement. This helps maintainers focus on critical code changes rather than manual code quality checks.
2.	Consistent Code Quality: With its real-time feedback, CodeFactor ensures adherence to coding standards and best practices, fostering a uniform and high-quality codebase across all contributors.
3.	Time-Saving for Maintainers: The automated reviews free up maintainers’ time, allowing them to focus on feature development and critical code issues while CodeFactor handles routine quality checks.
4.	Accessible and Easy to Use: CodeFactor seamlessly integrates with GitHub and provides a clear, visual report on code quality metrics, making it easy for contributors to understand and address code issues before merging.
5.	Transparent Quality Metrics: CodeFactor provides a public code quality score, which encourages contributors to submit higher-quality code and aligns with a collaborative, open-source approach to development.

Integrating CodeFactor would streamline the review process, improve the overall codebase quality, and allow for more effective collaboration between maintainers and contributors. I believe this would be a valuable addition to our repository’s workflow.

**Describe alternatives you've considered**

There are numerous other alternatives in GitHub MarketPlace. I chose this one because it was top of popularity and would be free.

**Additional context**

**Comment by sirkitree** [comment]
Yes please.

I'm interested to hear if anyone else has exp with ai code reviewers. Pros or cons in your experience?
