### ISSUE TITLE
This command: pnpm start --characters="characters/tate.character.json" results in an error

### ISSUE THREAD

**Issue by 619** [ai16z/eliza#817]
**Describe the bug**
running pnpm start --characters="characters/tate.character.json" results in this error "Error fetching response: SyntaxError: Unexpected token 'A', "Agent not found" is not valid JSON"

**To Reproduce**
Run pnpm start --characters="characters/tate.character.json" in the root folder

**Expected behavior**
It would be nice if it worked

**Comment by shakkernerd** [comment]
Hi @619 

After looking into this and tested locally, `pnpm start --characters=CHARACTER_FILE.json` works well with no issue.

Do you mind looking into the format and contents of your `tate.character.json` file ?
Looks to me like the issue is from the character file itself.

**Comment by jack-landon** [comment]
@619 If you still need the fix,

Run `pnpm approve builds`
You'll get a dropdown -> select better-sqlite3 and enter.
Then try again.
