### ISSUE TITLE
Client Twitter Login issue: Error: {"errors":[{"code":399,"message":"Incorrect. Please try again."}]}

### ISSUE THREAD

**Issue by MSghais** [ai16z/eliza#905]
**Describe the bug**

When I try to test the Twitter client, I get this message in the loading twitter client error.

Error: {"errors":[{"code":399,"message":"Incorrect. Please try again."}]}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Lukapetro** [comment]
Most likely, the data you entered in the environment variables is incorrect. Check them

**Comment by nfwGytautas** [comment]
Got the same it seems to be related to suspicious login checks from X

**Comment by metatxn** [comment]
> Got the same it seems to be related to suspicious login checks from X

+1, even i'm getting same issue. I created a new account for the agent.

**Comment by aj47** [comment]
for those trying to set eliza up on a vps
from the discord: 
```
Managed to login to twitter finally by spoofing the browser for VPS
For anyone that is having trouble this is way easier than setting up graphic interface or VPN

used Firefox settings > Network settings > manual proxy config 

Set SOCKS Host to 127.0.0.1 on port 8080
ssh -D 127.0.0.1:8080 user@<vps ip address>. 
#this using Mac/Windows you may need to generate keys

Then use firefox browser to login and complete verification
```

i wasn't able to do this succesfully but if someone can take this knowledge and suggest another way would be greaytly appreciated

**Comment by metatxn** [comment]
@aj47 it didn't work :(

**Comment by 0xfortes** [comment]
Followed @aj47 procedure and it works! Solved!

**Comment by KarimovMurodilla** [comment]
Same problem...

**Comment by ZhiminHeGit** [comment]
why is this closed?  it's not fixed.

**Comment by zkvm** [comment]
> for those trying to set eliza up on a vps from the discord:
> 
> ```
> Managed to login to twitter finally by spoofing the browser for VPS
> For anyone that is having trouble this is way easier than setting up graphic interface or VPN
> 
> used Firefox settings > Network settings > manual proxy config 
> 
> Set SOCKS Host to 127.0.0.1 on port 8080
> ssh -D 127.0.0.1:8080 user@<vps ip address>. 
> #this using Mac/Windows you may need to generate keys
> 
> Then use firefox browser to login and complete verification
> ```
> 
> i wasn't able to do this succesfully but if someone can take this knowledge and suggest another way would be greaytly appreciated

thanks it works

**Comment by metatxn** [comment]
@zkvm @0xfortes did you deploy it on cloud? Its working fine when running on localhost but i deployed it on cloud then getting suspicious notification on twitter.

**Comment by issa-me-sush** [comment]
yep this worked

**Comment by issa-me-sush** [comment]
> for those trying to set eliza up on a vps from the discord:
> 
> ```
> Managed to login to twitter finally by spoofing the browser for VPS
> For anyone that is having trouble this is way easier than setting up graphic interface or VPN
> 
> used Firefox settings > Network settings > manual proxy config 
> 
> Set SOCKS Host to 127.0.0.1 on port 8080
> ssh -D 127.0.0.1:8080 user@<vps ip address>. 
> #this using Mac/Windows you may need to generate keys
> 
> Then use firefox browser to login and complete verification
> ```
> 
> i wasn't able to do this succesfully but if someone can take this knowledge and suggest another way would be greaytly appreciated

yep this worked thanks!

**Comment by baties** [comment]
I have the same issue and none of the solutions even using an openVPN connection and login to the account with the same IP address helped me !
My AI agent still can not login to its twitter account !!
All the credential are okay. I double checked it.

**Comment by bercly0b** [comment]
same here..

**Comment by bercly0b** [comment]
https://github.com/elizaOS/eliza/issues/2225#issuecomment-2590563306
this solution works for me
