### ISSUE TITLE
Time Interval of generateNewTweetLoop is not consistent with the comment

### ISSUE THREAD

**Issue by SotoAlt** [ai16z/eliza#92]
on src/clients/twitter/generate.ts

export class TwitterGenerationClient extends ClientBase {
  onReady() {
    const generateNewTweetLoop = () => {
      this.generateNewTweet();
      setTimeout(
        generateNewTweetLoop,
        (Math.floor(Math.random() * (45 - 15 + 1)) + 15) * 60 * 1000,
      ); // Random interval between 4-8 hours
      
      **its actually 15-45 minutes, not 4-8 hours as the comment suggests.**
      
      
     Also IMO, all the time intervals, replies and search and engage are was too aggressive, I got my agent banned on X in less than 12 hrs of using in on the default settings, maybe we can have way more time intervals to avoid this by default

**Comment by lalalune** [comment]
We should probably figure out a way to control this. It could be a setting, for tweets / day.
