### ISSUE TITLE
Can't start project. Got `ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL` error

### ISSUE THREAD

**Issue by ntourne** [ai16z/eliza#925]
**Describe the bug**

I can't run the agent following the [Getting Started](https://ai16z.github.io/eliza/docs/quickstart/) docs.
I got this error:
```
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @ai16z/agent@0.1.5-alpha.5 start: `node --loader ts-node/esm src/index.ts "--isRoot" "--character=characters/trump.character.json"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**

```
git clone https://github.com/ai16z/eliza.git

cd eliza

git checkout $(git describe --tags --abbrev=0)
# v0.1.5-alpha.5

pnpm install

pnpm build

cp .env.example .env
# Didn't make any change

```

Finally, tried to start the agent:

```
pnpm start --character="characters/trump.character.json"
```

**Expected behavior**

I would spect the agent to start without issues.

**Additional context**

My local env:
```
Node: v23.3.0
pnpm: v9.15.0
Python: v3.11.6
```

**Comment by kennytan41** [comment]
same error

**Comment by shakkernerd** [comment]
Hi @ntourne What is your OS ?

**Comment by ileana-pr** [comment]
Looks like missing dependency... try to clean and rebuild: 

pnpm clean 
pnpm install 
pnpm build 

pnpm add -w -D ts-node typescript @types/node

**Comment by ntourne** [comment]
@shakkernerd: Fixed, thanks!
I ran what @ileana-pr shared:

```
pnpm clean
pnpm install
pnpm build

pnpm add -w -D ts-node typescript @types/node
```
