### ISSUE TITLE
Twitter/X Cache Login not staying logged in

### ISSUE THREAD

**Issue by salparadi** [ai16z/eliza#939]
**Describe the bug**

Added Twitter cookies per the docs and every time I run things, it triggers a new login alert from Twitter so something seems off. Considered trying the cookies from a logged in browser, but it uses the x.com domain, and when you try to add those, startup complains about the wrong domain. Login works, posting works, it just seems that the cookies should work to not trigger new logins each time. Guessing at some point Twitter will flag continuous logins like this. If I don't add cookies at all, same thing, it works, but triggers a login alert email each time.

**To Reproduce**

Simply starting Eliza with Twitter credentials added + manual cookies. They do get cached in the db, but on restart, it still doesn't consider itself logged in and I get an email.

**Expected behavior**

Stay logged in. Don't trigger a new login email alert from Twitter.

**Comment by netdragonx** [comment]
Believe above issue is addressed in [PR #856](https://github.com/ai16z/eliza/pull/856)
