### ISSUE TITLE
How to set the model class for Anthropic?

### ISSUE THREAD

**Issue by tdergouzi** [ai16z/eliza#988]
character.ts
```
    clients: [Clients.TWITTER],
    modelProvider: ModelProviderName.ANTHROPIC,
    settings: {
        model: ModelClass.MEDIUM,
    },
 ```
 when the agent start, the logs shows:
```
 ℹ INFORMATIONS
   Generating text with options: 
   {"modelProvider":"anthropic","model":"small"} 

 ℹ INFORMATIONS
   Selected model: 
   claude-3-haiku-20240307 
 ```
 
I don't know why the config is not useful. Anyone can help, Thanks a lot.

**Comment by salparadi** [comment]
Those sizes are hard coded into the package files. I think they are being decoupled, but for now you'd need to manually update the files (For Twitter: post.ts, interactions.ts)
